### ISSUE TITLE
Following recommended Maven structure for custom projects, license header verification plugin is included

### ISSUE THREAD

**Issue by aborroy** [Alfresco/alfresco-java-sdk#119]
When using suggested dependency for pom.xml in samples folder...

```
  <parent>
    <groupId>org.alfresco</groupId>
    <artifactId>alfresco-java-sdk</artifactId>
    <version>5.1.2</version>
  </parent>
```

... license Maven plugin is included. That provokes a simple `mvn clean package` command to fail if some source code in not including a license header.

Using default Spring Boot dependency is enough and license plugin is not included.

```
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.4.2</version>
        <relativePath/>
    </parent>
```

Sample projects shouldn't include parent dependency from `alfresco-java-sdk` project.

**Comment by jlosornogil** [comment]
PR to fix this parent issue -> https://github.com/Alfresco/alfresco-java-sdk/pull/149
