### ISSUE TITLE
Allow createNode() to also provide content.

### ISSUE THREAD

**Issue by binduwavell** [Alfresco/alfresco-java-sdk#177]
The swagger specification for createNode() indicates that a multi-part form can be used to create a node, with type, properties, permissions, etc AND with content.

The current client requires two API calls (createNode() and updateNodeContent()) because the generated createNode() does not properly expose the multi-part form encoding.

Please enhance the Java client for NodesApi to allow for the creation of a node and uploading of content in a single API call.

In a clustered environment there are edge cases where doing this as two API calls can result in concurrent modification and other exceptions. Workarounds like pinning clients to servers and delaying the updateNodeContent() call for a while so the cluster can properly quiess are not desirable workarounds.

**Comment by binduwavell** [comment]
It looks like a partial solution was added in #109, unfortunately that allow uploading content with a defined name and type but not to set properties, associations, etc.

**Comment by pjoshi31** [comment]
Hi @binduwavell , As you said the createNode() does not properly expose the multi-part encoding, Can you please elaborate, what's issue are being faced?

**Comment by MohinishSah** [comment]
It has been a long time and there is no confirmation from the reporter hence we are closing this ticket. If you are still facing some issue please feel free to raise a new issue.
Thanks!
