### ISSUE TITLE
Content API - createNode bug on version params

### ISSUE THREAD

**Issue by CarlosDiez-inetum** [Alfresco/alfresco-java-sdk#202]
I am using createNode method of Content API  (v5.2.2), but Feign client is not processing the parameters 'majorVersion' or 'versioningEnabled'. It results in a node without cm:versionable aspect whatever value you set.

Those params in createNode method (Node API) are working properly and creates cm:versionable aspect and its properties (cm:versionLabel, etc.).

**Comment by pardhukota-pk** [comment]
@CarlosDiez-inetum 
I replicated the issue and noticed that I am able to see “cm:versionable“ in the node's aspect. “cm:versionable“ is not the default aspect and we need to add it manually by choosing==> Manage Aspects=>select the aspect we want to add=>apply. But, if we set the value of “versioningEnabled” to false in the request, we will not see this in the aspect, even though we add it manually
![aspect](https://github.com/Alfresco/alfresco-java-sdk/assets/130377171/30b0d3a7-b74a-4987-9a70-5a0411e63974)
![select_aspect](https://github.com/Alfresco/alfresco-java-sdk/assets/130377171/da06eebf-7870-4e5b-bf54-ea62b532d7e8)

**Comment by pardhukota-pk** [comment]
@CarlosDiez-inetum Could you please confirm ?

**Comment by CarlosDiez-inetum** [comment]
Hi @pardhukota-pk,

Could you please check again because using createNode (NodesApi) I have never added manually the aspect versionable, because is taking it from the params: majorVersion (false) and versioningEnabled (true).

Since createNode (ContentApi) has those params, the behaviour of the method should be the same. 

Could you please check createNode from NodesApi vs ContentApi, setting majorVersion (false) and versioningEnabled (true)? It has the same behaviour? If not please advice this on SDK5 docs or fix it

Regards,
Carlos

**Comment by pardhukota-pk** [comment]
Hi @CarlosDiez-inetum 

I've re-tested the scenario using createNode() of ContenApi.

**Scenario 1:** While invoking createNode() of ContentApi with parameters **majorVersion (false) and versioningEnabled (true)**, I can see that the "cm:versionable" aspect is added to the node.

Please refer the attached screen captures (majorVersion-false.versionEnabled-true.mp4)

**Scenario 2:** While invoking createNode() of ContentApi with parameters **majorVersion (false) and versioningEnabled (false)**, I can see that the node is created without versionable aspect.

Please refer the attached screen captures (majorVersion-false.versionEnabled-false.mp4)

Both the APIs(ContentApi and NodesApi) are behaving similarly as expected. Could you please re-verify at your end ?


https://github.com/Alfresco/alfresco-java-sdk/assets/130377171/0cf02001-71bd-4b90-a1f9-b25430292335


https://github.com/Alfresco/alfresco-java-sdk/assets/130377171/addbecf5-dfc5-448c-a9b7-2eb995fb1e0e

**Comment by MohinishSah** [comment]
It has been a long time and there is no confirmation from the reporter hence we are closing this ticket. If you are still facing some issue please feel free to raise a new issue.
Thanks!
