### ISSUE TITLE
Sample not working

### ISSUE THREAD

**Issue by federicotarantino** [Alfresco/alfresco-java-sdk#207]
Hi, if I try to start "extension-template" sample, I have this error:

Field nodesApi in org.alfresco.sdk.sample.handler.HtmlContentCreatedHandler required a bean of type 'org.alfresco.core.handler.NodesApi' that could not be found.

Can you check Spring Boot configuration?

**Comment by rrajoria** [comment]
Hi @federicotarantino ,

I tried to start  "extension-template"  sample using the steps mentioned in [Readme.md](https://github.com/Alfresco/alfresco-java-sdk/blob/develop/samples/extension-template/README.md)   and I didn't got any error related to NodesApi not found.

Could you please let us know what steps you have used to start  "extension-template"  sample.

**Comment by federicotarantino** [comment]
Hi @rrajoria ,
it depends from spring boot version. I was using last stable version of java sdk (5.2.2) with Spring Boot 3. It not works.
Using 6.0-SNAPSHOT with Spring Boot 3 it works..

You can close this issue

Thanks

**Comment by rrajoria** [comment]
@federicotarantino  Thanks for the confirmation.
