### ISSUE TITLE
Add support for Model API

### ISSUE THREAD

**Issue by AFaust** [Alfresco/alfresco-java-sdk#73]
Today it surprised me that even though SDK 5 was released alongside ACS 7, it does not (yet) support the new [Model API](https://api-explorer.alfresco.com/api-explorer/?urls.primaryName=Model%20API). While I can sort-of understand the reason for not supporting the Workflow API (Alfresco's long-term goal is to phase out the embedded workflow engine), the Model API is kind of important, e.g. for event-handling automation where I might need to check "is-subType-of" relationships for nodes on which an event has been triggered to know whether a specific automation needs to be applied. Without access to the model definitions, this is currently impossible, except by doing a (rather stupid) check via an FTS search query like `TYPE:"acme:typeToTest" AND ID:"nodeUuid"`, which obviously is not reliable because it would have to go to SOLR, as TMQ does not support the ID field.

**Comment by mmartinadanx** [comment]
To be added in 5.1.1

**Comment by jlosornogil** [comment]
PR to add support for model API -> https://github.com/Alfresco/alfresco-java-sdk/pull/146
