### ISSUE TITLE
unavailability of the authentication related classes

### ISSUE THREAD

**Issue by omprakash-iiim** [Alfresco/alfresco-java-sdk#77]
While using the auth-rest-api dependency, I found that authentication related api interfaces are not present in the dependencies like AuthenticationApi, TicketBody.

**Comment by mmartinadanx** [comment]
Hi @omprakash-iiim can you share your pom?

**Comment by omprakash-iiim** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.amazonaws.kendra.connectors</groupId>
	<artifactId>aws-kendra-alfresco-connector</artifactId>
	<version>1.1-SNAPSHOT</version>
	<properties>
		<java.version>11</java.version>
	</properties>

	
	<repositories>
		<repository>
			<id>alfresco-public</id>
			<url>https://artifacts.alfresco.com/nexus/content/groups/public</url>
		</repository>
		<repository>
			<id>alfresco-public-snapshots</id>
			<url>https://artifacts.alfresco.com/nexus/content/groups/public-snapshots</url>
		</repository>
	</repositories>

	<dependencies>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
			<version>2.5.4</version>
		</dependency>
                <dependency>
                    <groupId>org.alfresco</groupId>
                    <artifactId>alfresco-auth-rest-api</artifactId>
                    <version>5.0.4</version>
                </dependency>
                <dependency>
                    <groupId>org.alfresco</groupId>
                    <artifactId>alfresco-core-rest-api</artifactId>
                    <version>5.0.4</version>
                </dependency>
		<dependency>
			<groupId>org.alfresco</groupId>
			<artifactId>alfresco-java-rest-api-spring-boot-starter</artifactId>
			<version>5.0.4</version>
		</dependency>
		
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.8.1</version>
				<configuration>
					<release>11</release>
					<annotationProcessorPaths>
						**
						<path>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
							<version>1.18.16</version>
						</path>
						**
					</annotationProcessorPaths>
				</configuration>
			</plugin>

			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<version>2.5.4</version>
			</plugin>
		</plugins>
	</build>
</project>

**Comment by omprakash-iiim** [comment]
Hi @mmartinadanx ,

Did you able to find the root cause?

Thanks

**Comment by mmartinadanx** [comment]
Hi @omprakash-iiim, looking at this now

**Comment by jlosornogil** [comment]
PR to fix authentication related classes -> https://github.com/Alfresco/alfresco-java-sdk/pull/148
